const ProjectService = {
  getProjects: function() {
    return new Promise((resolve, reject) => {
      setTimeout(function() {
        // var didSucceed = Math.random() >= 0.5;
        // didSucceed ? resolve(new Date()) :reject('Error');
        resolve([
          {id:1, theme:"reflex-silver", name:"Simple Project Name", pinned:false, numberOfTasks: 21},
          {id:2, theme:"ocean-blue", name:"Project Name", pinned:false, numberOfTasks: 329},
          {id:3, theme:"firebrick", name:"Hello World", pinned:false, numberOfTasks: 121},
        ])
      }, 2000);
    })
  },
  getTasksByProjectId: function (id) {
    return new Promise((resolve, reject) => {
      setTimeout(function() {
        // var didSucceed = Math.random() >= 0.5;
        // didSucceed ? resolve(new Date()) : reject('Error');
        resolve(
          {
            id:id,
            project: "Other one",
            tasks:[
              {
                id:21,
                status:'start',
                project: {id: 2, name:"Projects"+id},
                categories:[{id:1, name:'important'}],
                assigner: {id:33232121, avatar:'https://material-ui.com/static/images/avatar/1.jpg'},
                assignee:  {id:132321, avatar:'https://material-ui.com/static/images/avatar/2.jpg'},
                title: "Simple title and simple description", description:"This is some dumb description",
                notes:[
                  {id:121, author:"Ivan Vulovic", title:"Note 1", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aut doloribus eligendi iure magni maxime mollitia nisi. Earum excepturi iusto nostrum reiciendis saepe tempora vitae voluptates. Debitis, dicta, vitae! Aperiam cumque eos esse nisi, obcaecati quisquam! Aliquam aperiam architecto dignissimos eligendi facilis, iure laborum magni neque nihil porro repellendus repudiandae soluta, ut. Ab aspernatur assumenda atque consequatur consequuntur corporis cum earum eos error esse ex expedita fugiat hic ipsam ipsum iure magnam maxime mollitia nemo nesciunt obcaecati odio officia quas quasi quidem quo quod reiciendis repellat sapiente sequi sint, vero voluptate voluptatum. Animi aspernatur autem cumque debitis, dignissimos eius esse eveniet maiores, minima minus possimus quibusdam ratione suscipit, ut vitae! Alias asperiores consectetur facilis natus perspiciatis quas sit voluptatibus? Animi architecto aut, consequatur corporis deserunt fuga itaque iusto libero, maxime, necessitatibus non possimus repellendus rerum totam voluptatibus! Alias aliquid blanditiis consectetur consequuntur delectus ea incidunt quam reprehenderit repudiandae vel! A accusamus corporis culpa cupiditate delectus deserunt distinctio incidunt iure libero magni non officiis, reiciendis ut. Alias aliquam amet, atque cupiditate delectus dicta doloremque earum incidunt inventore ipsum molestiae nam nobis numquam porro sapiente tenetur vel, voluptatum. Doloremque exercitationem incidunt non provident vero? Ad aliquam cumque, cupiditate eveniet numquam optio recusandae."},
                  {id:122, author:"Marko Markovic", title:"Note 2", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo nihil porro veritatis? Accusantium iste quisquam ratione tenetur vero? Ab amet aut consectetur, deleniti earum eos in ipsam libero, necessitatibus nesciunt officia porro quisquam, ratione sequi similique sit suscipit temporibus unde. Aspernatur commodi consequuntur doloribus excepturi facere fugit hic nulla possimus tempore veniam. Aliquam animi ipsam labore quia quibusdam rem vero! Assumenda libero nulla obcaecati quaerat quisquam tempore ullam. Ab at consequuntur culpa cumque exercitationem harum, hic, illo impedit ipsa laboriosam maiores omnis quaerat ratione, rem repellendus reprehenderit sit temporibus. Deserunt eius eum fuga illum porro quos repellendus sit suscipit unde."},
                  {id:123, author:"Milos Ljubisavljevic", title:"Note 3", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi eum eveniet fuga inventore sapiente sunt. Alias aliquid asperiores autem beatae cupiditate distinctio doloremque ea et id illum in, ipsa iste iusto magnam nesciunt non odit optio pariatur placeat, porro quasi quia quo reiciendis, reprehenderit sint soluta sunt. Ex in, molestiae!"},
                  {id:124, author:"Mika Peric", title:"Note 4", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aut doloribus eligendi iure magni maxime mollitia nisi. Earum excepturi iusto nostrum reiciendis saepe tempora vitae voluptates. Debitis, dicta, vitae! Aperiam cumque eos esse nisi, obcaecati quisquam! Aliquam aperiam architecto dignissimos eligendi facilis, iure laborum magni neque nihil porro repellendus repudiandae soluta, ut. Ab aspernatur assumenda atque consequatur consequuntur corporis cum earum eos error esse ex expedita fugiat hic ipsam ipsum iure magnam maxime mollitia nemo nesciunt obcaecati odio officia quas quasi quidem quo quod reiciendis repellat sapiente sequi sint, vero voluptate voluptatum. Animi aspernatur autem cumque debitis, dignissimos eius esse eveniet maiores, minima minus possimus quibusdam ratione suscipit, ut vitae! Alias asperiores consectetur facilis natus perspiciatis quas sit voluptatibus? Animi architecto aut, consequatur corporis deserunt fuga itaque iusto libero, maxime, necessitatibus non possimus repellendus rerum totam voluptatibus! Alias aliquid blanditiis consectetur consequuntur delectus ea incidunt quam reprehenderit repudiandae vel! A accusamus corporis culpa cupiditate delectus deserunt distinctio incidunt iure libero magni non officiis, reiciendis ut. Alias aliquam amet, atque cupiditate delectus dicta doloremque earum incidunt inventore ipsum molestiae nam nobis numquam porro sapiente tenetur vel, voluptatum. Doloremque exercitationem incidunt non provident vero? Ad aliquam cumque, cupiditate eveniet numquam optio recusandae."},
                  {id:125, author:"Ivan Vulovic", title:"Note 5", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga laudantium neque odio soluta. A ab, aliquam asperiores assumenda doloribus dolorum ducimus eligendi enim et eveniet expedita facilis laudantium magni molestias numquam obcaecati odit possimus quasi quisquam repellendus, sed tempora velit. Atque corporis, illum itaque iusto labore laborum necessitatibus perspiciatis quam?"}
                ]
              },
              {id:22, categories:[{id:2, name:'overdue'}], status:'start',  project: {id: 2, name:"Projects 2"},
                assigner: {id:33232121, avatar:'https://material-ui.com/static/images/avatar/1.jpg'},
                assignee:  {id:132321, avatar:'https://material-ui.com/static/images/avatar/2.jpg'},
                title: "Simple title and simple description", description:"This is some dumb description",
                notes:[
                  {id:221, author:"Ivan Vulovic", title:"Note 1", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aut doloribus eligendi iure magni maxime mollitia nisi. Earum excepturi iusto nostrum reiciendis saepe tempora vitae voluptates. Debitis, dicta, vitae! Aperiam cumque eos esse nisi, obcaecati quisquam! Aliquam aperiam architecto dignissimos eligendi facilis, iure laborum magni neque nihil porro repellendus repudiandae soluta, ut. Ab aspernatur assumenda atque consequatur consequuntur corporis cum earum eos error esse ex expedita fugiat hic ipsam ipsum iure magnam maxime mollitia nemo nesciunt obcaecati odio officia quas quasi quidem quo quod reiciendis repellat sapiente sequi sint, vero voluptate voluptatum. Animi aspernatur autem cumque debitis, dignissimos eius esse eveniet maiores, minima minus possimus quibusdam ratione suscipit, ut vitae! Alias asperiores consectetur facilis natus perspiciatis quas sit voluptatibus? Animi architecto aut, consequatur corporis deserunt fuga itaque iusto libero, maxime, necessitatibus non possimus repellendus rerum totam voluptatibus! Alias aliquid blanditiis consectetur consequuntur delectus ea incidunt quam reprehenderit repudiandae vel! A accusamus corporis culpa cupiditate delectus deserunt distinctio incidunt iure libero magni non officiis, reiciendis ut. Alias aliquam amet, atque cupiditate delectus dicta doloremque earum incidunt inventore ipsum molestiae nam nobis numquam porro sapiente tenetur vel, voluptatum. Doloremque exercitationem incidunt non provident vero? Ad aliquam cumque, cupiditate eveniet numquam optio recusandae."},
                  {id:222, author:"Marko Markovic", title:"Note 2", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo nihil porro veritatis? Accusantium iste quisquam ratione tenetur vero? Ab amet aut consectetur, deleniti earum eos in ipsam libero, necessitatibus nesciunt officia porro quisquam, ratione sequi similique sit suscipit temporibus unde. Aspernatur commodi consequuntur doloribus excepturi facere fugit hic nulla possimus tempore veniam. Aliquam animi ipsam labore quia quibusdam rem vero! Assumenda libero nulla obcaecati quaerat quisquam tempore ullam. Ab at consequuntur culpa cumque exercitationem harum, hic, illo impedit ipsa laboriosam maiores omnis quaerat ratione, rem repellendus reprehenderit sit temporibus. Deserunt eius eum fuga illum porro quos repellendus sit suscipit unde."},
                  {id:223, author:"Milos Ljubisavljevic", title:"Note 3", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi eum eveniet fuga inventore sapiente sunt. Alias aliquid asperiores autem beatae cupiditate distinctio doloremque ea et id illum in, ipsa iste iusto magnam nesciunt non odit optio pariatur placeat, porro quasi quia quo reiciendis, reprehenderit sint soluta sunt. Ex in, molestiae!"},
                  {id:224, author:"Mika Peric", title:"Note 4", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aut doloribus eligendi iure magni maxime mollitia nisi. Earum excepturi iusto nostrum reiciendis saepe tempora vitae voluptates. Debitis, dicta, vitae! Aperiam cumque eos esse nisi, obcaecati quisquam! Aliquam aperiam architecto dignissimos eligendi facilis, iure laborum magni neque nihil porro repellendus repudiandae soluta, ut. Ab aspernatur assumenda atque consequatur consequuntur corporis cum earum eos error esse ex expedita fugiat hic ipsam ipsum iure magnam maxime mollitia nemo nesciunt obcaecati odio officia quas quasi quidem quo quod reiciendis repellat sapiente sequi sint, vero voluptate voluptatum. Animi aspernatur autem cumque debitis, dignissimos eius esse eveniet maiores, minima minus possimus quibusdam ratione suscipit, ut vitae! Alias asperiores consectetur facilis natus perspiciatis quas sit voluptatibus? Animi architecto aut, consequatur corporis deserunt fuga itaque iusto libero, maxime, necessitatibus non possimus repellendus rerum totam voluptatibus! Alias aliquid blanditiis consectetur consequuntur delectus ea incidunt quam reprehenderit repudiandae vel! A accusamus corporis culpa cupiditate delectus deserunt distinctio incidunt iure libero magni non officiis, reiciendis ut. Alias aliquam amet, atque cupiditate delectus dicta doloremque earum incidunt inventore ipsum molestiae nam nobis numquam porro sapiente tenetur vel, voluptatum. Doloremque exercitationem incidunt non provident vero? Ad aliquam cumque, cupiditate eveniet numquam optio recusandae."},
                  {id:225, author:"Ivan Vulovic", title:"Note 5", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga laudantium neque odio soluta. A ab, aliquam asperiores assumenda doloribus dolorum ducimus eligendi enim et eveniet expedita facilis laudantium magni molestias numquam obcaecati odit possimus quasi quisquam repellendus, sed tempora velit. Atque corporis, illum itaque iusto labore laborum necessitatibus perspiciatis quam?"}
                ]
              },
              {id:23, categories:[], status:'start', project: {id: 2, name:"Projects 2"},
                assigner: {id:12131311, avatar:'https://material-ui.com/static/images/avatar/7.jpg'},
                assignee:  {id:12323331, avatar:'https://material-ui.com/static/images/avatar/4.jpg'},
                title: "Add UglifyJS when compiling to production", description:"Range pickers pdf",
                notes:[
                  {id:321, author:"Ivan Vulovic", title:"Note 1", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aut doloribus eligendi iure magni maxime mollitia nisi. Earum excepturi iusto nostrum reiciendis saepe tempora vitae voluptates. Debitis, dicta, vitae! Aperiam cumque eos esse nisi, obcaecati quisquam! Aliquam aperiam architecto dignissimos eligendi facilis, iure laborum magni neque nihil porro repellendus repudiandae soluta, ut. Ab aspernatur assumenda atque consequatur consequuntur corporis cum earum eos error esse ex expedita fugiat hic ipsam ipsum iure magnam maxime mollitia nemo nesciunt obcaecati odio officia quas quasi quidem quo quod reiciendis repellat sapiente sequi sint, vero voluptate voluptatum. Animi aspernatur autem cumque debitis, dignissimos eius esse eveniet maiores, minima minus possimus quibusdam ratione suscipit, ut vitae! Alias asperiores consectetur facilis natus perspiciatis quas sit voluptatibus? Animi architecto aut, consequatur corporis deserunt fuga itaque iusto libero, maxime, necessitatibus non possimus repellendus rerum totam voluptatibus! Alias aliquid blanditiis consectetur consequuntur delectus ea incidunt quam reprehenderit repudiandae vel! A accusamus corporis culpa cupiditate delectus deserunt distinctio incidunt iure libero magni non officiis, reiciendis ut. Alias aliquam amet, atque cupiditate delectus dicta doloremque earum incidunt inventore ipsum molestiae nam nobis numquam porro sapiente tenetur vel, voluptatum. Doloremque exercitationem incidunt non provident vero? Ad aliquam cumque, cupiditate eveniet numquam optio recusandae."},
                  {id:322, author:"Marko Markovic", title:"Note 2", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo nihil porro veritatis? Accusantium iste quisquam ratione tenetur vero? Ab amet aut consectetur, deleniti earum eos in ipsam libero, necessitatibus nesciunt officia porro quisquam, ratione sequi similique sit suscipit temporibus unde. Aspernatur commodi consequuntur doloribus excepturi facere fugit hic nulla possimus tempore veniam. Aliquam animi ipsam labore quia quibusdam rem vero! Assumenda libero nulla obcaecati quaerat quisquam tempore ullam. Ab at consequuntur culpa cumque exercitationem harum, hic, illo impedit ipsa laboriosam maiores omnis quaerat ratione, rem repellendus reprehenderit sit temporibus. Deserunt eius eum fuga illum porro quos repellendus sit suscipit unde."},
                  {id:323, author:"Milos Ljubisavljevic", title:"Note 3", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi eum eveniet fuga inventore sapiente sunt. Alias aliquid asperiores autem beatae cupiditate distinctio doloremque ea et id illum in, ipsa iste iusto magnam nesciunt non odit optio pariatur placeat, porro quasi quia quo reiciendis, reprehenderit sint soluta sunt. Ex in, molestiae!"},
                  {id:324, author:"Mika Peric", title:"Note 4", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aut doloribus eligendi iure magni maxime mollitia nisi. Earum excepturi iusto nostrum reiciendis saepe tempora vitae voluptates. Debitis, dicta, vitae! Aperiam cumque eos esse nisi, obcaecati quisquam! Aliquam aperiam architecto dignissimos eligendi facilis, iure laborum magni neque nihil porro repellendus repudiandae soluta, ut. Ab aspernatur assumenda atque consequatur consequuntur corporis cum earum eos error esse ex expedita fugiat hic ipsam ipsum iure magnam maxime mollitia nemo nesciunt obcaecati odio officia quas quasi quidem quo quod reiciendis repellat sapiente sequi sint, vero voluptate voluptatum. Animi aspernatur autem cumque debitis, dignissimos eius esse eveniet maiores, minima minus possimus quibusdam ratione suscipit, ut vitae! Alias asperiores consectetur facilis natus perspiciatis quas sit voluptatibus? Animi architecto aut, consequatur corporis deserunt fuga itaque iusto libero, maxime, necessitatibus non possimus repellendus rerum totam voluptatibus! Alias aliquid blanditiis consectetur consequuntur delectus ea incidunt quam reprehenderit repudiandae vel! A accusamus corporis culpa cupiditate delectus deserunt distinctio incidunt iure libero magni non officiis, reiciendis ut. Alias aliquam amet, atque cupiditate delectus dicta doloremque earum incidunt inventore ipsum molestiae nam nobis numquam porro sapiente tenetur vel, voluptatum. Doloremque exercitationem incidunt non provident vero? Ad aliquam cumque, cupiditate eveniet numquam optio recusandae."},
                  {id:325, author:"Ivan Vulovic", title:"Note 5", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga laudantium neque odio soluta. A ab, aliquam asperiores assumenda doloribus dolorum ducimus eligendi enim et eveniet expedita facilis laudantium magni molestias numquam obcaecati odit possimus quasi quisquam repellendus, sed tempora velit. Atque corporis, illum itaque iusto labore laborum necessitatibus perspiciatis quam?"}
                ]
              },
              {id:24,
                categories:[{id:1, name:"important"}],
                status:'progress',
                project: {id: 2, name:"Projects 2"},
                assigner: {id:13221, avatar:'https://material-ui.com/static/images/avatar/3.jpg'},
                assignee:  {id:123232321, avatar:'https://material-ui.com/static/images/avatar/4.jpg'},
                title: "Title 2", description:"For some other stuff",
                notes:[
                  {id:421, author:"Ivan Vulovic", title:"Note 1", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aut doloribus eligendi iure magni maxime mollitia nisi. Earum excepturi iusto nostrum reiciendis saepe tempora vitae voluptates. Debitis, dicta, vitae! Aperiam cumque eos esse nisi, obcaecati quisquam! Aliquam aperiam architecto dignissimos eligendi facilis, iure laborum magni neque nihil porro repellendus repudiandae soluta, ut. Ab aspernatur assumenda atque consequatur consequuntur corporis cum earum eos error esse ex expedita fugiat hic ipsam ipsum iure magnam maxime mollitia nemo nesciunt obcaecati odio officia quas quasi quidem quo quod reiciendis repellat sapiente sequi sint, vero voluptate voluptatum. Animi aspernatur autem cumque debitis, dignissimos eius esse eveniet maiores, minima minus possimus quibusdam ratione suscipit, ut vitae! Alias asperiores consectetur facilis natus perspiciatis quas sit voluptatibus? Animi architecto aut, consequatur corporis deserunt fuga itaque iusto libero, maxime, necessitatibus non possimus repellendus rerum totam voluptatibus! Alias aliquid blanditiis consectetur consequuntur delectus ea incidunt quam reprehenderit repudiandae vel! A accusamus corporis culpa cupiditate delectus deserunt distinctio incidunt iure libero magni non officiis, reiciendis ut. Alias aliquam amet, atque cupiditate delectus dicta doloremque earum incidunt inventore ipsum molestiae nam nobis numquam porro sapiente tenetur vel, voluptatum. Doloremque exercitationem incidunt non provident vero? Ad aliquam cumque, cupiditate eveniet numquam optio recusandae."},
                  {id:422, author:"Marko Markovic", title:"Note 2", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo nihil porro veritatis? Accusantium iste quisquam ratione tenetur vero? Ab amet aut consectetur, deleniti earum eos in ipsam libero, necessitatibus nesciunt officia porro quisquam, ratione sequi similique sit suscipit temporibus unde. Aspernatur commodi consequuntur doloribus excepturi facere fugit hic nulla possimus tempore veniam. Aliquam animi ipsam labore quia quibusdam rem vero! Assumenda libero nulla obcaecati quaerat quisquam tempore ullam. Ab at consequuntur culpa cumque exercitationem harum, hic, illo impedit ipsa laboriosam maiores omnis quaerat ratione, rem repellendus reprehenderit sit temporibus. Deserunt eius eum fuga illum porro quos repellendus sit suscipit unde."},
                  {id:423, author:"Milos Ljubisavljevic", title:"Note 3", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi eum eveniet fuga inventore sapiente sunt. Alias aliquid asperiores autem beatae cupiditate distinctio doloremque ea et id illum in, ipsa iste iusto magnam nesciunt non odit optio pariatur placeat, porro quasi quia quo reiciendis, reprehenderit sint soluta sunt. Ex in, molestiae!"},
                  {id:424, author:"Mika Peric", title:"Note 4", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aut doloribus eligendi iure magni maxime mollitia nisi. Earum excepturi iusto nostrum reiciendis saepe tempora vitae voluptates. Debitis, dicta, vitae! Aperiam cumque eos esse nisi, obcaecati quisquam! Aliquam aperiam architecto dignissimos eligendi facilis, iure laborum magni neque nihil porro repellendus repudiandae soluta, ut. Ab aspernatur assumenda atque consequatur consequuntur corporis cum earum eos error esse ex expedita fugiat hic ipsam ipsum iure magnam maxime mollitia nemo nesciunt obcaecati odio officia quas quasi quidem quo quod reiciendis repellat sapiente sequi sint, vero voluptate voluptatum. Animi aspernatur autem cumque debitis, dignissimos eius esse eveniet maiores, minima minus possimus quibusdam ratione suscipit, ut vitae! Alias asperiores consectetur facilis natus perspiciatis quas sit voluptatibus? Animi architecto aut, consequatur corporis deserunt fuga itaque iusto libero, maxime, necessitatibus non possimus repellendus rerum totam voluptatibus! Alias aliquid blanditiis consectetur consequuntur delectus ea incidunt quam reprehenderit repudiandae vel! A accusamus corporis culpa cupiditate delectus deserunt distinctio incidunt iure libero magni non officiis, reiciendis ut. Alias aliquam amet, atque cupiditate delectus dicta doloremque earum incidunt inventore ipsum molestiae nam nobis numquam porro sapiente tenetur vel, voluptatum. Doloremque exercitationem incidunt non provident vero? Ad aliquam cumque, cupiditate eveniet numquam optio recusandae."},
                  {id:425, author:"Ivan Vulovic", title:"Note 5", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga laudantium neque odio soluta. A ab, aliquam asperiores assumenda doloribus dolorum ducimus eligendi enim et eveniet expedita facilis laudantium magni molestias numquam obcaecati odit possimus quasi quisquam repellendus, sed tempora velit. Atque corporis, illum itaque iusto labore laborum necessitatibus perspiciatis quam?"}
                ]},
              {id:25, categories:[{id:3, name:'bookmark'}], status:'done',  project: {id: 2, name:"Projects 2"},
                assigner: {id:123441, avatar:'https://material-ui.com/static/images/avatar/5.jpg'},
                assignee:  {id:15452321, avatar:'https://material-ui.com/static/images/avatar/6.jpg'},
                title: "Title 3", description:"Colors here",
                notes:[
                  {id:521, author:"Ivan Vulovic", title:"Note 1", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aut doloribus eligendi iure magni maxime mollitia nisi. Earum excepturi iusto nostrum reiciendis saepe tempora vitae voluptates. Debitis, dicta, vitae! Aperiam cumque eos esse nisi, obcaecati quisquam! Aliquam aperiam architecto dignissimos eligendi facilis, iure laborum magni neque nihil porro repellendus repudiandae soluta, ut. Ab aspernatur assumenda atque consequatur consequuntur corporis cum earum eos error esse ex expedita fugiat hic ipsam ipsum iure magnam maxime mollitia nemo nesciunt obcaecati odio officia quas quasi quidem quo quod reiciendis repellat sapiente sequi sint, vero voluptate voluptatum. Animi aspernatur autem cumque debitis, dignissimos eius esse eveniet maiores, minima minus possimus quibusdam ratione suscipit, ut vitae! Alias asperiores consectetur facilis natus perspiciatis quas sit voluptatibus? Animi architecto aut, consequatur corporis deserunt fuga itaque iusto libero, maxime, necessitatibus non possimus repellendus rerum totam voluptatibus! Alias aliquid blanditiis consectetur consequuntur delectus ea incidunt quam reprehenderit repudiandae vel! A accusamus corporis culpa cupiditate delectus deserunt distinctio incidunt iure libero magni non officiis, reiciendis ut. Alias aliquam amet, atque cupiditate delectus dicta doloremque earum incidunt inventore ipsum molestiae nam nobis numquam porro sapiente tenetur vel, voluptatum. Doloremque exercitationem incidunt non provident vero? Ad aliquam cumque, cupiditate eveniet numquam optio recusandae."},
                  {id:522, author:"Marko Markovic", title:"Note 2", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo nihil porro veritatis? Accusantium iste quisquam ratione tenetur vero? Ab amet aut consectetur, deleniti earum eos in ipsam libero, necessitatibus nesciunt officia porro quisquam, ratione sequi similique sit suscipit temporibus unde. Aspernatur commodi consequuntur doloribus excepturi facere fugit hic nulla possimus tempore veniam. Aliquam animi ipsam labore quia quibusdam rem vero! Assumenda libero nulla obcaecati quaerat quisquam tempore ullam. Ab at consequuntur culpa cumque exercitationem harum, hic, illo impedit ipsa laboriosam maiores omnis quaerat ratione, rem repellendus reprehenderit sit temporibus. Deserunt eius eum fuga illum porro quos repellendus sit suscipit unde."},
                  {id:523, author:"Milos Ljubisavljevic", title:"Note 3", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi eum eveniet fuga inventore sapiente sunt. Alias aliquid asperiores autem beatae cupiditate distinctio doloremque ea et id illum in, ipsa iste iusto magnam nesciunt non odit optio pariatur placeat, porro quasi quia quo reiciendis, reprehenderit sint soluta sunt. Ex in, molestiae!"},
                  {id:524, author:"Mika Peric", title:"Note 4", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aut doloribus eligendi iure magni maxime mollitia nisi. Earum excepturi iusto nostrum reiciendis saepe tempora vitae voluptates. Debitis, dicta, vitae! Aperiam cumque eos esse nisi, obcaecati quisquam! Aliquam aperiam architecto dignissimos eligendi facilis, iure laborum magni neque nihil porro repellendus repudiandae soluta, ut. Ab aspernatur assumenda atque consequatur consequuntur corporis cum earum eos error esse ex expedita fugiat hic ipsam ipsum iure magnam maxime mollitia nemo nesciunt obcaecati odio officia quas quasi quidem quo quod reiciendis repellat sapiente sequi sint, vero voluptate voluptatum. Animi aspernatur autem cumque debitis, dignissimos eius esse eveniet maiores, minima minus possimus quibusdam ratione suscipit, ut vitae! Alias asperiores consectetur facilis natus perspiciatis quas sit voluptatibus? Animi architecto aut, consequatur corporis deserunt fuga itaque iusto libero, maxime, necessitatibus non possimus repellendus rerum totam voluptatibus! Alias aliquid blanditiis consectetur consequuntur delectus ea incidunt quam reprehenderit repudiandae vel! A accusamus corporis culpa cupiditate delectus deserunt distinctio incidunt iure libero magni non officiis, reiciendis ut. Alias aliquam amet, atque cupiditate delectus dicta doloremque earum incidunt inventore ipsum molestiae nam nobis numquam porro sapiente tenetur vel, voluptatum. Doloremque exercitationem incidunt non provident vero? Ad aliquam cumque, cupiditate eveniet numquam optio recusandae."},
                  {id:525, author:"Ivan Vulovic", title:"Note 5", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga laudantium neque odio soluta. A ab, aliquam asperiores assumenda doloribus dolorum ducimus eligendi enim et eveniet expedita facilis laudantium magni molestias numquam obcaecati odit possimus quasi quisquam repellendus, sed tempora velit. Atque corporis, illum itaque iusto labore laborum necessitatibus perspiciatis quam?"}
                ]},
              {id:26, categories:[{id:4, name:'observe'}], status:'start', project: {id: 2, name:"Projects 2"},
                assigner: {id:13421, avatar:'https://material-ui.com/static/images/avatar/5.jpg'},
                assignee:  {id:123121, avatar:'https://material-ui.com/static/images/avatar/6.jpg'},
                title: "Not complicated task", description:"Read about this",
                notes:[
                  {id:621, author:"Ivan Vulovic", title:"Note 1", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aut doloribus eligendi iure magni maxime mollitia nisi. Earum excepturi iusto nostrum reiciendis saepe tempora vitae voluptates. Debitis, dicta, vitae! Aperiam cumque eos esse nisi, obcaecati quisquam! Aliquam aperiam architecto dignissimos eligendi facilis, iure laborum magni neque nihil porro repellendus repudiandae soluta, ut. Ab aspernatur assumenda atque consequatur consequuntur corporis cum earum eos error esse ex expedita fugiat hic ipsam ipsum iure magnam maxime mollitia nemo nesciunt obcaecati odio officia quas quasi quidem quo quod reiciendis repellat sapiente sequi sint, vero voluptate voluptatum. Animi aspernatur autem cumque debitis, dignissimos eius esse eveniet maiores, minima minus possimus quibusdam ratione suscipit, ut vitae! Alias asperiores consectetur facilis natus perspiciatis quas sit voluptatibus? Animi architecto aut, consequatur corporis deserunt fuga itaque iusto libero, maxime, necessitatibus non possimus repellendus rerum totam voluptatibus! Alias aliquid blanditiis consectetur consequuntur delectus ea incidunt quam reprehenderit repudiandae vel! A accusamus corporis culpa cupiditate delectus deserunt distinctio incidunt iure libero magni non officiis, reiciendis ut. Alias aliquam amet, atque cupiditate delectus dicta doloremque earum incidunt inventore ipsum molestiae nam nobis numquam porro sapiente tenetur vel, voluptatum. Doloremque exercitationem incidunt non provident vero? Ad aliquam cumque, cupiditate eveniet numquam optio recusandae."},
                  {id:622, author:"Marko Markovic", title:"Note 2", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo nihil porro veritatis? Accusantium iste quisquam ratione tenetur vero? Ab amet aut consectetur, deleniti earum eos in ipsam libero, necessitatibus nesciunt officia porro quisquam, ratione sequi similique sit suscipit temporibus unde. Aspernatur commodi consequuntur doloribus excepturi facere fugit hic nulla possimus tempore veniam. Aliquam animi ipsam labore quia quibusdam rem vero! Assumenda libero nulla obcaecati quaerat quisquam tempore ullam. Ab at consequuntur culpa cumque exercitationem harum, hic, illo impedit ipsa laboriosam maiores omnis quaerat ratione, rem repellendus reprehenderit sit temporibus. Deserunt eius eum fuga illum porro quos repellendus sit suscipit unde."},
                  {id:623, author:"Milos Ljubisavljevic", title:"Note 3", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi eum eveniet fuga inventore sapiente sunt. Alias aliquid asperiores autem beatae cupiditate distinctio doloremque ea et id illum in, ipsa iste iusto magnam nesciunt non odit optio pariatur placeat, porro quasi quia quo reiciendis, reprehenderit sint soluta sunt. Ex in, molestiae!"},
                  {id:624, author:"Mika Peric", title:"Note 4", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aut doloribus eligendi iure magni maxime mollitia nisi. Earum excepturi iusto nostrum reiciendis saepe tempora vitae voluptates. Debitis, dicta, vitae! Aperiam cumque eos esse nisi, obcaecati quisquam! Aliquam aperiam architecto dignissimos eligendi facilis, iure laborum magni neque nihil porro repellendus repudiandae soluta, ut. Ab aspernatur assumenda atque consequatur consequuntur corporis cum earum eos error esse ex expedita fugiat hic ipsam ipsum iure magnam maxime mollitia nemo nesciunt obcaecati odio officia quas quasi quidem quo quod reiciendis repellat sapiente sequi sint, vero voluptate voluptatum. Animi aspernatur autem cumque debitis, dignissimos eius esse eveniet maiores, minima minus possimus quibusdam ratione suscipit, ut vitae! Alias asperiores consectetur facilis natus perspiciatis quas sit voluptatibus? Animi architecto aut, consequatur corporis deserunt fuga itaque iusto libero, maxime, necessitatibus non possimus repellendus rerum totam voluptatibus! Alias aliquid blanditiis consectetur consequuntur delectus ea incidunt quam reprehenderit repudiandae vel! A accusamus corporis culpa cupiditate delectus deserunt distinctio incidunt iure libero magni non officiis, reiciendis ut. Alias aliquam amet, atque cupiditate delectus dicta doloremque earum incidunt inventore ipsum molestiae nam nobis numquam porro sapiente tenetur vel, voluptatum. Doloremque exercitationem incidunt non provident vero? Ad aliquam cumque, cupiditate eveniet numquam optio recusandae."},
                  {id:625, author:"Ivan Vulovic", title:"Note 5", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga laudantium neque odio soluta. A ab, aliquam asperiores assumenda doloribus dolorum ducimus eligendi enim et eveniet expedita facilis laudantium magni molestias numquam obcaecati odit possimus quasi quisquam repellendus, sed tempora velit. Atque corporis, illum itaque iusto labore laborum necessitatibus perspiciatis quam?"}
                ]},
              {id:27, categories:[{id:4, name:'observe'},{id:5, name:'snooze'},{id:6, name:'archive'}], status:'start', project: {id: 2, name:"Projects 2"},
                assigner: {id:12131311, avatar:'https://material-ui.com/static/images/avatar/7.jpg'},
                assignee:  {id:12323331, avatar:'https://material-ui.com/static/images/avatar/4.jpg'},
                title: "Add UglifyJS when compiling to production", description:"Range pickers pdf",
                notes:[
                  {id:721, author:"Ivan Vulovic", title:"Note 1", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aut doloribus eligendi iure magni maxime mollitia nisi. Earum excepturi iusto nostrum reiciendis saepe tempora vitae voluptates. Debitis, dicta, vitae! Aperiam cumque eos esse nisi, obcaecati quisquam! Aliquam aperiam architecto dignissimos eligendi facilis, iure laborum magni neque nihil porro repellendus repudiandae soluta, ut. Ab aspernatur assumenda atque consequatur consequuntur corporis cum earum eos error esse ex expedita fugiat hic ipsam ipsum iure magnam maxime mollitia nemo nesciunt obcaecati odio officia quas quasi quidem quo quod reiciendis repellat sapiente sequi sint, vero voluptate voluptatum. Animi aspernatur autem cumque debitis, dignissimos eius esse eveniet maiores, minima minus possimus quibusdam ratione suscipit, ut vitae! Alias asperiores consectetur facilis natus perspiciatis quas sit voluptatibus? Animi architecto aut, consequatur corporis deserunt fuga itaque iusto libero, maxime, necessitatibus non possimus repellendus rerum totam voluptatibus! Alias aliquid blanditiis consectetur consequuntur delectus ea incidunt quam reprehenderit repudiandae vel! A accusamus corporis culpa cupiditate delectus deserunt distinctio incidunt iure libero magni non officiis, reiciendis ut. Alias aliquam amet, atque cupiditate delectus dicta doloremque earum incidunt inventore ipsum molestiae nam nobis numquam porro sapiente tenetur vel, voluptatum. Doloremque exercitationem incidunt non provident vero? Ad aliquam cumque, cupiditate eveniet numquam optio recusandae."},
                  {id:722, author:"Marko Markovic", title:"Note 2", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo nihil porro veritatis? Accusantium iste quisquam ratione tenetur vero? Ab amet aut consectetur, deleniti earum eos in ipsam libero, necessitatibus nesciunt officia porro quisquam, ratione sequi similique sit suscipit temporibus unde. Aspernatur commodi consequuntur doloribus excepturi facere fugit hic nulla possimus tempore veniam. Aliquam animi ipsam labore quia quibusdam rem vero! Assumenda libero nulla obcaecati quaerat quisquam tempore ullam. Ab at consequuntur culpa cumque exercitationem harum, hic, illo impedit ipsa laboriosam maiores omnis quaerat ratione, rem repellendus reprehenderit sit temporibus. Deserunt eius eum fuga illum porro quos repellendus sit suscipit unde."},
                  {id:723, author:"Milos Ljubisavljevic", title:"Note 3", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi eum eveniet fuga inventore sapiente sunt. Alias aliquid asperiores autem beatae cupiditate distinctio doloremque ea et id illum in, ipsa iste iusto magnam nesciunt non odit optio pariatur placeat, porro quasi quia quo reiciendis, reprehenderit sint soluta sunt. Ex in, molestiae!"},
                  {id:724, author:"Mika Peric", title:"Note 4", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aut doloribus eligendi iure magni maxime mollitia nisi. Earum excepturi iusto nostrum reiciendis saepe tempora vitae voluptates. Debitis, dicta, vitae! Aperiam cumque eos esse nisi, obcaecati quisquam! Aliquam aperiam architecto dignissimos eligendi facilis, iure laborum magni neque nihil porro repellendus repudiandae soluta, ut. Ab aspernatur assumenda atque consequatur consequuntur corporis cum earum eos error esse ex expedita fugiat hic ipsam ipsum iure magnam maxime mollitia nemo nesciunt obcaecati odio officia quas quasi quidem quo quod reiciendis repellat sapiente sequi sint, vero voluptate voluptatum. Animi aspernatur autem cumque debitis, dignissimos eius esse eveniet maiores, minima minus possimus quibusdam ratione suscipit, ut vitae! Alias asperiores consectetur facilis natus perspiciatis quas sit voluptatibus? Animi architecto aut, consequatur corporis deserunt fuga itaque iusto libero, maxime, necessitatibus non possimus repellendus rerum totam voluptatibus! Alias aliquid blanditiis consectetur consequuntur delectus ea incidunt quam reprehenderit repudiandae vel! A accusamus corporis culpa cupiditate delectus deserunt distinctio incidunt iure libero magni non officiis, reiciendis ut. Alias aliquam amet, atque cupiditate delectus dicta doloremque earum incidunt inventore ipsum molestiae nam nobis numquam porro sapiente tenetur vel, voluptatum. Doloremque exercitationem incidunt non provident vero? Ad aliquam cumque, cupiditate eveniet numquam optio recusandae."},
                  {id:725, author:"Ivan Vulovic", title:"Note 5", description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga laudantium neque odio soluta. A ab, aliquam asperiores assumenda doloribus dolorum ducimus eligendi enim et eveniet expedita facilis laudantium magni molestias numquam obcaecati odit possimus quasi quisquam repellendus, sed tempora velit. Atque corporis, illum itaque iusto labore laborum necessitatibus perspiciatis quam?"}
                ]},
            ]
          }
        )
      }, 2000);
    })
  }
};

export default ProjectService;
