export default [
  {id:'reflex-silver', name: 'Reflex Silver'},
  {id:'ocean-blue', name: 'Ocean Blue'},
  {id:'new-leaf', name: 'New Leaf'},
  {id:'leaf', name: 'Leaf'},
  {id:'ultramarine', name: 'Ultramarine'},
  {id:'pixle-dust', name: 'Pixle Dust'},
  {id:'neon-glow', name: 'Neon Glow'},
  {id:'spring-greens', name: 'Spring Greens'},
  {id:'luscious-lime', name: 'Luscious Lime'},
  {id:'firebrick', name: 'Firebrick'},
  {id:'mars', name: 'Mars'},
  {id:'sanguine', name: 'Sanguine'},
  {id:'fizzy-peach', name: 'Fizzy Peach'},
  {id:'pink-sugar', name: 'Pink Sugar'},
  {id:'fresh-papaya', name: 'Fresh Papaya'},
  {id:'lemon-drizzle', name: 'Lemon Drizzle'},
  {id:'victoria-purple', name: 'Victoria Purple'},
  {id:'purple-lake', name: 'Purple Lake'},
  {id:'evening-light', name: 'Evening Light'},
  {id:'sweet-dream', name: 'Sweet Dream'},
  {id:'pink', name: 'Pink'},
  {id:'berry-smoothie', name: 'Berry Smoothie'},
  {id:'mystic-muave', name: 'Mystic Muave'}
];
